### ISSUE TITLE
Help with Command

### ISSUE THREAD

**Issue by MechEng70** [whyakari/getProps#2]
Issue: When running the "`./gen_custom_pif.sh json your_build.prop`" command, the script claims that "No build.prop files found in script directory".

What build.prop should this be pointed to?  See image for attempts to use the system.prop and module.prop in the extracted_images folder.

Attempted to use the ./extracted_images that is indicated by "Saved to".

![Screenshot_20231205-075306_JuiceSSH](https://github.com/whyakari/getProps/assets/11697710/66beea5f-ec17-4e4f-b1bc-d6ae0d2bbc55)

**Comment by whyakari** [comment]
sorry for the delay in responding.

so, after you extract you need to do this
```shell
cp ./**/**/{system,module}.prop .
mv system.prop build.prop
```

after 
```shell
./gen_custom_pif.sh json build.prop
```

**Comment by MechEng70** [comment]
Thank you. 

Now this custom.pif.json replaces the root/data/adb as pif.json
